linuxdeepin/.github

.github/workflows/jenkins-bridge.yml, workflow-templates/call-jenkins-bridge.properties.json, workflow-templates/call-jenkins-bridge.yml
It could trigger internal "github-pipeline" Jenkins job.
Log:
=> feat: add jenkins-bridge

.github/workflows/commitlint.yml
fix wrong commitlint download link
Log:
=> fix: commitlint download link

.github/workflows/templates-sync.yml, README.md
=> feat: add action-sync

.github/workflows/templates-sync.yml
sync failed when change file "repos/linuxdeepin/.gitkeep"
limit sync action's suffix
Log:
=> fix: actions sync failed

.github/workflows/organization-manager.yml, README.md, organization.yaml
=> feat: add organization-manager

.github/workflows/organization-manager.yml
limit organization-manager repo and branch
Log:
=> chore: limit organization-manager repo and branch

workflow-templates/chatOps.yml
=> feat: add chatOps

workflow-templates/cppcheck.json, workflow-templates/cppcheck.yml
=> feat: add cppcheck

repos/linuxdeepin/.github.json
enable commitlint for .github
Log:
=> feat: enable commitlint for .github

.github/workflows/organization-manager.yml, .github/workflows/templates-sync.yml, workflow-templates/call-commitlint.yml, workflow-templates/call-jenkins-bridge.yml, workflow-templates/cppcheck.yml
Docs: https://docs.github.com/en/enterprise-server@3.2/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
Log:
=> feat: Only cancel in-progress jobs or runs for the current workflow

workflow-templates/call-commitlint.yml, workflow-templates/call-jenkins-bridge.yml
=> fix: workflow-templates wrong branch

.github/workflows/templates-sync.yml
=> fix: cant sync new project's template file

.github/workflows/organization-manager.yml
=> feat: 更新action organization manager

.github/workflows/organization-manager.yml
=> fix: 修复版本号

workflow-templates/call-commitlint.yml, workflow-templates/call-jenkins-bridge.yml, workflow-templates/cppcheck.yml
change to github.event.number
Log:
=> fix: github.ref is not pr number when pull_request_target

organization.yaml, repos/linuxdeepin/deepin-gtk-theme.json
workflow template sync to deepin-gtk-theme
Log:
=> feat: add deepin-gtk-theme config

repos/linuxdeepin/deepin-gtk-theme.json
deepin-gtk-theme remove cppcheck
Log:
=> chore: deepin-gtk-theme remove cppcheck

.github/workflows/organization-manager.yml, organization.yaml
=> feat: 关闭项目的allow merge commit选项

workflow-templates/chatOps.yml
=> feat: chatOps rebase and merge

workflow-templates/chatOps.yml
=> fix: chatOps typo

organization.yaml
=> feat: disable issues

.github/workflows/build-deb.yml, repos/linuxdeepin/deepin-camera.json, repos/linuxdeepin/deepin-gtk-theme.json, repos/linuxdeepin/deepin-manual.json, repos/linuxdeepin/deepin-music.json, workflow-templates/call-build-deb.properties.json, workflow-templates/call-build-deb.yml
rename jenkins-bridge to build-deb
Log:
=> feat: rename jenkins-bridge to build-deb

organization.yaml, repos/linuxdeepin/qt5platform-plugins.json
organization manager add qt5platform-plugins
action template sync add qt5platform-plugins
Log:
=> feat: add qt5platform-plugins project

repos/linuxdeepin/deepin-camera.json
=> fix: 修复同步工作流丢失

commitlint/commitlint.config.js
update commitlint helpUrl
Log:
=> chore: update commitlint helpUrl

workflow-templates/cppcheck.yml
Remove cppcheck when closing the pull request
=> fix: remove cppcheck when closing the pull request

.github/workflows/chatOps.yml
fix chatOps no workflow_call
Log:
=> fix: chatOps no workflow_call

organization.yaml, repos/linuxdeepin/deepin-font-manager.json
sync action template to deepin-font-manager
add branch protection to deepin-font-manager
Log:
=> feat: add deepin-font-manager project config

repos/linuxdeepin/action-.json
backup all github action repo
Log:
=> feat: backup all github action repo

organization.yaml, repos/linuxdeepin/dtkcommon.json
organization manager add dtkcommon
action template sync add dtkcommon
Log:
=> feat: add dtkcommon project

organization.yaml, repos/linuxdeepin/dtkcore.json, repos/linuxdeepin/dtkgui.json, repos/linuxdeepin/dtkwidget.json, repos/linuxdeepin/qt5integration.json, repos/linuxdeepin/qt5platform-plugins.json
organization manager add dtkcore, dtkgui, dtkwidget, qt5integration
action template sync add dtkcore, dtkgui, dtkwidget, qt5integration
dtk projects only use master branch
Log:
=> feat: add dtk projects

.github/workflows/backup-all-repos-to-gitee.bash, .github/workflows/backup-all-repos-to-gitee.yml
Backup all repos to gitee on a schedule
Log:
=> feat: backup all repos to gitee

.github/workflows/chatOps.yml
Devopt workflow Allow menber with write permission to use '/merge' command
Log:
=> feat: Allow member with write permission use merge

.github/workflows/backup-all-repos-to-gitee.bash, .github/workflows/backup-all-repos-to-gitee.yml
=> fix: gitee仓库被设置成私有

.github/workflows/teams-manager.yml, README.md
add teams-manager workflow
Log:
=> feat: add teams-manager workflow

.github/workflows/teams-manager.yml, teams.yaml
add teams.yaml, generated by https://github.com/linuxdeepin/.github/runs/5863465230
Log:
=> feat: add teams.yaml

teams.yaml
Admins team maintain all repositories
Log:
=> feat: Admins team maintain all repositories

commitlint/commitlint.config.js
update commitlint help url
Log:
=> chore: update commitlint help url

teams.yaml
add members for deepin-anything.
Log: add members.
=> feat: add members for deepin-anything.

teams.yaml
add one teamer for dde-file-manager,gio-qt,udisks-qt
=> feat: add one teamer for dde-file-manager,gio-qt,udisks-qt

teams.yaml
add zimo-liu to students team
Log:
=> chore: add zimo-liu to students team

.github/ISSUE_TEMPLATE/config.yaml, organization.yaml, repos/linuxdeepin/deepin-anything.json, repos/linuxdeepin/gio-qt.json, repos/linuxdeepin/udisks2-qt5.json
为新增项目增加工作流配置文件
Log: 为新增项目增加工作流配置文件
=> chore: add workflow for newly migrated projects

teams.yaml
add members for deepin-system-monitor.
=> feat: add members for deepin-system-monitor.

teams.yaml
add members for deepin-face and depends.
Log: add members.
=> feat: add members for deepin-face

organization.yaml, repos/linuxdeepin/deepin-system-monitor.json, teams.yaml
修正 teams.yaml 格式错误，添加系统监视器相关检查
相关：https://github.com/linuxdeepin/.github/pull/82
Log: 修正 teams.yaml 格式错误，添加系统监视器相关检查
=> fix: teams.yaml format, add check for system-monitor

teams.yaml
feat: 终端添加github管理员权限
终端添加github管理员权限
Log: 终端添加github管理员权限
=> feat: 终端社区迁移

teams.yaml
添加deepin-calculator管理权限
Log: 添加deepin-calculator管理权限
=> feat: 添加deepin-calculator管理权限

organization.yaml, repos/linuxdeepin/deepin-calculator.json, repos/linuxdeepin/deepin-face.json
为人脸识别模块与计算器增加 CI 检查
Log: 为人脸识别模块与计算器增加 CI 检查
=> chore: add CI and branch protection for deepin-face and calculator

organization.yaml, repos/linuxdeepin/deepin-terminal.json
为 deepin-terminal 增加 CI 工作流管线
Log: 为 deepin-terminal 增加 CI 工作流管线
=> chore: add CI pipeline for deepin-terminal

organization.yaml, repos/linuxdeepin/dde-control-center.json, repos/linuxdeepin/dde-file-manager.json
为文件管理器与控制中心配置 CI
Log: 为文件管理器与控制中心配置 CI
=> chore: add CI workflow for file-manager and control-center

teams.yaml
add members for dde-grand-search
=> feat: add members for dde-grand-search

teams.yaml
add members for dde-control-center.
Log: add members for dde-control-center.
=> feat: add members for dde-control-center

organization.yaml, repos/linuxdeepin/dde-grand-search.json
为全局搜索组件项目添加 CI 配置
Log: 为全局搜索组件项目添加 CI 配置
=> chore: add CI pipeline for dde-grand-search

.github/workflows/chatOps.yml
When check falis due to internal error, you can use '/check' to rerigger the pull request checks
Log:
=> feat: add retrigger check command

teams.yaml
调整权限配置文件。
相关：https://github.com/linuxdeepin/.github/pull/97
Log: 调整权限配置文件
=> fix: wrong teams.yaml config

teams.yaml
添加音视频项目权限配置
Log: 添加音视频项目权限配置
/review  @zccrs
=> fix: 添加音视频项目权限配置

organization.yaml, repos/linuxdeepin/deepin-screen-recorder.json
=> chore: CI and branch config for screen recorder

teams.yaml
Add DDE permission configuration
Log: Add DDE permission configuration
=> fix: Add DDE permission configuration

teams.yaml
修复 teams.yaml 配置文件的语法问题
Log: 修复 teams.yaml 配置文件的语法问题
=> fix: teams.yaml syntax

teams.yaml
=> 调整Students分组人员信息

organization.yaml, repos/linuxdeepin/dde-account-faces.json, repos/linuxdeepin/dde-clipboard.json, repos/linuxdeepin/dde-dock.json, repos/linuxdeepin/dde-manual-content.json, repos/linuxdeepin/dde-network-core.json, repos/linuxdeepin/dde-polkit-agent.json, repos/linuxdeepin/dde-wallpapers.json, repos/linuxdeepin/deepin-gettext-tools.json, repos/linuxdeepin/deepin-pw-check.json
第二波 DDE 仓库的 CI 配置和分支保护
另见：https://github.com/linuxdeepin/.github/pull/113
=> chore: add another batch of config for DDE repos

teams.yaml
Add deepin-kwin  permission configuration.
Log: Add deepin-kwin  permission configuration.
=> feat: Add deepin-kwin  permission configuration.

organization.yaml, repos/linuxdeepin/dde-kwin.json, repos/linuxdeepin/deepin-kwin.json
kwin 相关仓库的分支保护和 CI 检查
Log: kwin 相关仓库的分支保护和 CI 检查
=> chore: kwin related repo config

teams.yaml
@wyu71 修改了 GitHub ID，更新对应的 id
Log: 更新音乐组维护者 id
=> fix: update username

organization.yaml, repos/linuxdeepin/dde-api.json, repos/linuxdeepin/dde-launcher.json, repos/linuxdeepin/dde-qt-dbus-factory.json, repos/linuxdeepin/lastore-daemon.json
第三波 dde 组件的分支保护和 CI 配置
这组完了后就剩下 gtk-theme 和 ab-recovery 了
=> chore: 3rd batch of dde repos

organization.yaml, repos/linuxdeepin/dde-wayland-config.json
添加 dde-wayland-config CI 和分支保护
Log: 添加 dde-wayland-config CI 和分支保护
=> chore: add dde-wayland-config CI and branch protection

.github/ISSUE_TEMPLATE/config.yml, .github/workflows/yamllint.yml, teams.yaml
增加 yamllint 检查
Log: 增加 yamllint 检查
=> feat: add yamllint

teams.yaml
=> fix: 修改欢迎项目管理权限

organization.yaml, repos/linuxdeepin/dde-introduction.json
dde-introduction CI 和分支保护
Log: dde-introduction 分支保护和 CI
=> chore: add dde-introduction CI check and branch protection

teams.yaml
=> feat: 软件包，归档社区迁移

organization.yaml, repos/linuxdeepin/deepin-compressor.json, repos/linuxdeepin/deepin-deb-installer.json
为 deb 安装器和归档管理器提供 CI 配置和分支保护
Log: 为 deb 安装器和归档管理器提供 CI 配置和分支保护
=> chore: add CI and branch config for deb-installer and compressor

.github/workflows/build-distribution.yaml, repos/linuxdeepin/deepin-desktop-base.json, workflow-templates/call-build-distribution.yml
add debian and archlinux distribution
Log:
=> feat: add distribution builder

repos/linuxdeepin/deepin-desktop-base.json
=> fix: source yaml -> yml

.github/workflows/build-distribution.yml
=> fix: missing secrets

.github/workflows/build-distribution.yml
使用 github.event.issue.pull_request 判断是否来自 pull request
Log:
=> fix: use github.event.issue.pull_request

repos/linuxdeepin/deepin-desktop-base.json
从 deepin-deb-installer 复制文件忘记修改路径
Log:
=> fix: stupid mistake

repos/linuxdeepin/deepin-desktop-schemas.json
=> feat: add deepin-desktop-schemas distribution builder

.github/workflows/build-distribution.yml, repos/linuxdeepin/dde-api.json, repos/linuxdeepin/dde-polkit-agent.json, repos/linuxdeepin/dde-qt-dbus-factory.json, repos/linuxdeepin/deepin-desktop-schemas.json, repos/linuxdeepin/deepin-gettext-tools.json, repos/linuxdeepin/deepin-gtk-theme.json, repos/linuxdeepin/deepin-sound-theme.json, repos/linuxdeepin/dpa-ext-gnomekeyring.json, repos/linuxdeepin/dtkcommon.json, repos/linuxdeepin/dtkcore.json, repos/linuxdeepin/dtkgui.json, repos/linuxdeepin/dtkwidget.json, repos/linuxdeepin/go-dbus-factory.json, repos/linuxdeepin/go-gir-generator.json, repos/linuxdeepin/go-lib.json, repos/linuxdeepin/go-x11-client.json, repos/linuxdeepin/startdde.json
=> feat: add distribution build

.github/workflows/build-distribution.yml
=> fix: disable debian build

teams.yaml
Description: 修改日志项目配置管理权限
Log: 修改日志项目配置管理权限
link:
=> fix: 修改日志项目配置管理权限

teams.yaml
Description: 添加五子棋项目维护权限
Log: 添加五子棋项目维护权限
=> chore: 添加五子棋项目维护权限

teams.yaml
=> chore: 添加语音记事本维护权限

organization.yaml, repos/linuxdeepin/deepin-log-viewer.json
=> chore: add ci and branch protection for log viewer

teams.yaml
Description: 增加deepin-clone维护者
Log:
=> fix: 增加deepin-clone维护者

teams.yaml
Description: 增加deepin-boot-maker维护者
Log:
=> feat: 增加deepin-boot-maker维护者

teams.yaml
Description: 添加连连看项目维护权限
Log: 添加连连看项目维护权限
=> chore: 添加连连看项目维护权限

teams.yaml
=> chore: integrated NanJing applications

.github/workflows/build-deb.yml
add github token to global env, Used to get author email
Log:
=> feat: add github token env

teams.yaml
Description: 增加 deepin-downloader 维护者
Log:
=> feat: 增加 deepin-downloader 维护者

teams.yaml
dde-app-services contains:
1. dde-dconfig-daemon(dbus daemon for dconfig)
2. dde-dconfig-editor(dconfig editor gui)
3. dde-dconfig(doncfig cli tools)
Log:
Influence: none
=> feat: add dde-app-services

.github/workflows/build-deb.yml
for testing apicheck pipeline
Log:
=> feat: trigger apicheck at build

teams.yaml
=> chore: 修改管理员用户名称

.github/workflows/build-distribution.yml
=> feat: update arch builder

.github/workflows/build-deb.yml
Add workflow for check if code has changed API
Log:
=> feat: Add apicheck job

.github/workflows/build-deb.yml
change id(request pull number) add to global env
Log:
=> feat: CHANGE ID moved to global env

.github/workflows/chatOps.yml
only rerequest the last check suites
Log:
=> fix: No more duplicate rerequest check

.github/workflows/build-deb.yml
print apicheck result at the stdout
Log:
=> feat: print apicheck result

.github/workflows/build-distribution.yml
not switch to right directory
Log:
=> fix: lock database error

.github/workflows/build-deb.yml
This reverts commit 7fb40293780152385def856cfcb606e50ac9025f.
=> Revert "Revert "feat: Add apicheck job""

teams.yaml
desc: 增加 deepin-diskmanager、deepin-fcitxconfigtool-plugin 维护者
Log: 增加 deepin-diskmanager、deepin-fcitxconfigtool-plugin 维护者
=> feat: 增加 deepin-diskmanager、deepin-fcitxconfigtool-plugin 维护者

repos/linuxdeepin/dde-wloutput-daemon.json
wloutput-daemon 的配置之前应该没生效，修改后重新触发一下使其生效
=> fix: wloutput-daemon re-configuration

teams.yaml
增加docparser相关人员名单
Log: 增加docparser
=> chore: 增加docparser相关人员名单

.github/workflows/build-deb.yml
ignore download artifact error
Log:
=> feat: continue when download artifact error

teams.yaml
add maintainer for grand search.
Log: add maintainer for grand search.
=> chore: add maintainer for grand search

.github/workflows/chatOps.yml
recoginzed command start with comment not contains
Log: commander contained in comment misrecoginzed
=> fix: commander contains in comment can be misrecoginzed

.github/workflows/build-distribution.yml
pull request missing git fetch
Log:
=> fix: cannot build debian and deepin

.github/workflows/build-distribution.yml
=> refactor: add version step

.github/workflows/build-distribution.yml
=> refactor: update arch build

repos/linuxdeepin/dde-account-faces.json, repos/linuxdeepin/dde-clipboard.json, repos/linuxdeepin/dde-control-center.json, repos/linuxdeepin/dde-daemon.json, repos/linuxdeepin/dde-dock.json, repos/linuxdeepin/dde-file-manager.json, repos/linuxdeepin/dde-kwin.json, repos/linuxdeepin/dde-launcher.json, repos/linuxdeepin/dde-network-core.json, repos/linuxdeepin/dde-session-shell.json, repos/linuxdeepin/dde-session-ui.json, repos/linuxdeepin/deepin-anything.json, repos/linuxdeepin/deepin-network-proxy.json, repos/linuxdeepin/deepin-pw-check.json, repos/linuxdeepin/deepin-turbo.json, repos/linuxdeepin/qt5integration.json, repos/linuxdeepin/qt5platform-plugins.json
- `dde-account-faces`
- `dde-clipboard`
- `dde-control-center`
- `dde-daemon`
- `dde-dock`
- `dde-file-manager`
- `dde-kwin`
- `dde-launcher`
- `dde-network-core`
- `dde-session-ui`
- `dde-session-shell`
- `deepin-anything`
- `deepin-pw-check`
- `deepin-turbo`
- `qt5integration`
- `qt5platform-plugins`
Log:
=> feat: add build-distribution

.github/workflows/build-distribution.yml
=> feat: update job name

.github/workflows/build-distribution.yml
If there is a hash of the pull request, set 1.0.0 as the version number.
Log:
=> fix: judgment condition error

.github/workflows/build-distribution.yml
=> fix: archlinux need clone full git

.github/workflows/build-distribution.yml
push action need git package
Log:
=> fix: not install git package

.github/workflows/build-distribution.yml
Ask to trust workspace after git upgrade.
https://github.com/actions/checkout/issues/766
Log:
=> fix: trusted github repository

.github/workflows/build-distribution.yml
tag=$(git describe --tags | cut -f1 -d '-') || echo
Log:
=> fix: missing tag

teams.yaml
=> chore: 添加日历信息

.github/workflows/build-distribution.yml
=> fix: no download of the specified product

teams.yaml
=> fix: 添加实用工具权限

teams.yaml
=> chore: remove team decl for people who no longer involved

.github/workflows/build-distribution.yml
=> fix: debian install devscripts

.github/workflows/build-distribution.yml
move devscripts to pbuilder hooks
Log:
=> fix: move devscripts to pbuilder hooks

teams.yaml
修改磁盘管理器和下载器权限
Log: 修改磁盘管理器和下载权限
=> fix: 修改磁盘管理器和下载器权限

.github/workflows/cla-check.yml, repos/linuxdeepin/deepin-riscv.json
add cla check
log: add cla check
=> feat: add cla check

.github/workflows/cla-check.yml, repos/linuxdeepin/deepin-riscv.json, workflow-templates/call-clacheck.yml
use call cla-check instead of cla-check
Log: fix cla config
=> fix: fix cla config

.github/workflows/cla-check.yml, workflow-templates/call-clacheck.properties.json, workflow-templates/call-clacheck.yml
add @uniontech.com @deepin.org @deepin.com to allow list
fix use call cla-check instead of cla-check
Log: add @uniontech.com @deepin.org @deepin.com to allow list
=> fix: add email allow list

repos/linuxdeepin/dde-manual-content.json
fix dde-manual-content mistyped as dde-manual
Log: fix dde-manual-content config
=> fix: fix dde-manual-content config

repos/linuxdeepin/deepin-fcitxconfigtool-plugin.json
fix deepin-fcitxconfigtool-pluginmistyped
Log: fix deepin-fcitxconfigtool-plugin
=> fix: fix deepin-fcitxconfigtool-plugin

teams.yaml
新增磁盘管理器和下载新成员
Log:新增磁盘管理器和下载新成员
=> fix: 修改磁盘管理器和下载器权限 -新增成员

repos/linuxdeepin/dtkdeclarative.json
dtkdeclarative支持构建archlinux、debian
=> Enable build distribution for dtkdeclarative

repos/linuxdeepin/dtkdeclarative.json
Amend 7049daa9f483027902120114353ebedc1e2f5bcb.
=> Fix workflow destination path in dtkdeclarative.json

workflow-templates/call-build-deb.yml
use pull_request_target close instead of pull_request close
Log: fix error workflow call
=> fix(call-build-deb): fix error workflow call

.github/workflows/build-distribution.yml
use justforlxz/deepin-builder-docker image
Log:
=> feat: update archlinux build

.github/workflows/build-distribution.yml
=> feat: only linuxdeepin will run upload

.github/workflows/build-distribution.yml
=> fix: only linuxdeepin run gpg steps

repos/linuxdeepin/linglong-hub.json
add backup(gitlab), commitlin, chatOps, cla-check to linglong-hub
Log: init linglong-hub github workflow
=> feat: init linglong-hub github workflow

teams.yaml
DDE成员添加前后端 项目的approved权限
Log: 添加DDE成员合并github代码的权限
Influence: 多数人参与review代码
=> chore: DDE成员添加approved权限

teams.yaml
增加一组配置，用以处理玲珑项目相关的 issue
cc @realwujing
=> chore: people who triage linglong issues

teams.yaml
=> fix: 修改磁盘管理器和下载器权限 -新增成员董鹏鹏

.github/workflows/build-distribution.yml
=> feat: check archlinux PKGBUILD exist

.github/workflows/cla-check.yml
do not lock pr afetr pr close
Log: do not lock pr asfter pr close
=> chore: do not lock pr after pr close

teams.yaml
linglong-hub permission adjust
Log: adjust linglong-hub permission
=> chore: adjust linglong permission

.github/workflows/build-distribution.yml
change deepin-community.github.io to 1000
Log:
=> feat: add debian repo priority

.github/workflows/build-deb.yml
use subcommand style
Log: use subcommand style
=> chore: add new style build deb

.github/workflows/build-deb.yml
fix triggerBuild --token
Log: fix triggerBuild --token
=> fix: fix triggerBuild --token

.github/workflows/build-linglong.yml, repos/linuxdeepin/linglong-hub.json, workflow-templates/call-build-linglong.yml
add linglong-builder workflow
Log: add linglong-builder
=> feat: add linglong-builder

repos/linuxdeepin/linglong-hub.json
fix error sync workflow filename
Log: fix error workflow filename
=> fix: fix error workflow filename

workflow-templates/call-build-linglong.yml
fix error linglong call
Log: fix error linglong call
=> fix: fix error linglong call

.github/workflows/build-linglong.yml
add CHANGE_ID
Log: add CHANGE_ID
=> fix: add lost CHANGE_ID

.github/workflows/build-linglong.yml, workflow-templates/call-build-linglong.yml
use environment for approve
Log: use environment for approve
=> fix: use environment for approve

teams.yaml
=> fix: should use push for write permission

.github/workflows/build-distribution.yml
https://community-packages.deepin.com/deepin is too slow
Log:
=> feat: use ftp.jaist.ac.jp mirror

organization.yaml, repos/linuxdeepin/dtk-template.json, teams.yaml
=> feat: add dtk-template

.github/workflows/license-check.yml, workflow-templates/call-license-check.yml
fix wrong continue-on-error usage
Log: wrong continue-on-error usage
=> fix: wrong continue-on-error usage

.github/workflows/license-check.yml
Add comment after LICENSE Check
Log: Add comment after LICENSE Check
=> feat: Add comment after LICENSE Check

.github/workflows/license-check.yml, workflow-templates/call-license-check.yml
fix comment permission
Log: fix comment permission
=> fix: comment permission

.github/workflows/license-check.yml
如果评论失败也不使检查失败，临时处理检查问题
实际问题仍需解决。
=> fix: don't fail check if comment failed

.github/workflows/doc-check.yml, repos/linuxdeepin/dtkcore.json, repos/linuxdeepin/dtkdeclarative.json, repos/linuxdeepin/dtkgui.json, repos/linuxdeepin/dtkwidget.json, workflow-templates/call-doc-chek.yml
add doc check for dtkcore,dtkdeclarative,dtkgui,dtkwidget
Log: add doc check
=> feat: add doc check

.github/workflows/license-check.yml, workflow-templates/call-license-check.yml
fix License Check
Log: fix: License Check
=> fix: License Check

.github/workflows/license-check.yml
默认折叠 REUSE 检查所展示的评论
Related: https://github.com/linuxdeepin/.github/pull/285
=> chore: collapse REUSE failed auto comment

workflow-templates/call-doc-check.yml
add required APP_PRIVATE_KEY
Log: add required APP_PRIVATE_KEY
=> fix: add required APP_PRIVATE_KEY

.github/workflows/chatOps.yml, .github/workflows/templates-sync.yml
Add '/' prefix to input when exec @check
=> feat(chatops): Exact match workflows name

teams.yaml
添加多媒体新成员
Log: 添加多媒体新成员
/review
@BLumia @zccrs
=> fix: 添加多媒体新成员

.github/workflows/backup-repo.yml, .github/workflows/backup-to-gitlab.yml
use workflow_cal instead itself
Log: split backup-to-gitlab
=> chore: split backup-to-gitlab

.github/workflows/backup-repo.yml
=> fix: fix typo

.github/workflows/backup-to-gitee.yml, .github/workflows/backup-to-gitlab.yml, .github/workflows/backup-to-gitlabwh.yml
gitee and gitlabwh spilted
Log: split into two files
=> chore: split into two files

.github/workflows/backup-to-gitee.yml, .github/workflows/backup-to-gitlabwh.yml, workflow-templates/backup-to-gitlab.yml
split backup into gitlabwh and gitee
Log: split into two files
=> chore: final merged

repos/linuxdeepin/deepin-movie-reborn.json
=> feat: deepin-movie-reborn add distribution build

teams.yaml
=> chore: adjust Admins group permission

teams.yaml
fix: 修改deepin-kwin权限
新增成员
Log: 新增成员
=> 新增deepin-kwin成员

teams.yaml
deepin-kwin添加成员
Log: deepin-kwin添加成员
=> fix: deepin-kwin添加成员

teams.yaml
add UniqueDing to deepin-kwin-member
Log: add UniqueDing to deepin-kwin-member
=> feat: add UniqueDing to deepin-kwin-member

teams.yaml
=> feat: update dde-file-manager teamers

teams.yaml
add xyruos to deepin-kwin and dde-kwin
Log: add xyruos to deepin-kwin and dde-kwin
=> fix: add xyruos to deepin-kwin and dde-kwin

teams.yaml
=> Updated teams.yaml.

repos/linuxdeepin/deepin-cursor-theme.json
=> chore: remove cppcheck from cursor-theme repo

teams.yaml
add deepin-plymouth
Log: add member
=> feat: add member

organization.yaml
branch protection for plymouth project, remove
deprecated cursor-theme project
=> chore: update branch protection

teams.yaml
add guoyao to dtk members
Log:
=> chore: add dtk member

teams.yaml
=> fix: Updated teams.yaml.

teams.yaml
Description: add deepin-fcitxconfigtool-plugin/deepin-boot-maker/deepin-clone develop
Log: add guonafu/Fire-dtx/SuperZhangxueming
=> chore: add develop member

repos/linuxdeepin/deepin-tweak.json
add deepin-tweak but not use backup-to-gitlab
Log:
=> feat: add deepin-tweak

.github/workflows/templates-sync.yml
adjust sync commit msg to fit gerrit commit msg check
Log: adjust commit msg
Influence: none
=> chore: adjust sync commit msg to fit gerrit check

repos/linuxdeepin/deepin-tweak.json
=> feat: remove call-build-deb

teams.yaml
chore: add toberyan to DTK  members
=> chore: add toberyan to DTK  members

teams.yaml
add dtk repositories
Log: add dtk repositories
=> chore: add dtk repositories

teams.yaml
add DDE maintainers
Log: add DDE maintainers
=> chor: add DDE maintainers

organization.yaml, repos/linuxdeepin/dtkaudiomanager.json, repos/linuxdeepin/dtkbluetooth.json, repos/linuxdeepin/dtkcrypt.json, repos/linuxdeepin/dtkdevice.json, repos/linuxdeepin/dtkdisplay.json, repos/linuxdeepin/dtkio.json, repos/linuxdeepin/dtkmultimedia.json, repos/linuxdeepin/dtknetwork.json, repos/linuxdeepin/dtknetworkmanager.json, repos/linuxdeepin/dtksystem.json, repos/linuxdeepin/dtksystemsettings.json
为新 DTK 组件进行 CI 和分支保护配置
注：仅添加了基础的 CI，由于这些新组建很多应该都无法进行构建，故目前未添加构建相关的 CI。
=> chore: CI and branch config for new dtk components

teams.yaml
add dde-control-center  maintainers
Log: add dde-control-center  maintainers
=> chore: add dde-control-center maintainers

teams.yaml
添加多媒体DTK权限和修改图形图形组成员权限
Log: 添加多媒体DTK权限和修改图形图形组成员权限
/review
@BLumia @zccrs
=> fix: 添加多媒体DTK权限和修改图形图形组成员权限

.github/workflows/doc-check.yml
=> fix: use commit repo for cmake

.github/workflows/build-distribution.yml
=> fix: doesn't prune remote tag

repos/linuxdeepin/deepin-camera.json, repos/linuxdeepin/deepin-deb-installer.json, repos/linuxdeepin/deepin-image-viewer.json, repos/linuxdeepin/deepin-log-viewer.json, repos/linuxdeepin/deepin-music.json
- deepin-camera
- deepin-deb-installer
- deepin-image-viewer
- deepin-log-viewer
- deepin-music
=> feat: add apps build

repos/linuxdeepin/dareader.json
=> feat: add dareader distribution build

teams.yaml
Added administrative rights for 'Deepin-kwayland'
=> feat: Added administrative rights for 'deepin-kwayland'

organization.yaml, repos/linuxdeepin/deepin-wallpapers-nonfree.json, teams.yaml
=> chore: add CI config for non-free wallpapers package

repos/linuxdeepin/dtkaudiomanager.json, repos/linuxdeepin/dtkbluetooth.json, repos/linuxdeepin/dtkcrypt.json, repos/linuxdeepin/dtkdevice.json, repos/linuxdeepin/dtkdisplay.json, repos/linuxdeepin/dtkio.json, repos/linuxdeepin/dtkmultimedia.json, repos/linuxdeepin/dtknetwork.json, repos/linuxdeepin/dtknetworkmanager.json, repos/linuxdeepin/dtksystem.json, repos/linuxdeepin/dtksystemsettings.json
=> feat: dtk add build-deb and build-distrobution

.github/workflows/cla-check.yml, teams.yaml
添加飞腾作为企业贡献者
cc @tsic404 @gujian
=> chore: add Phytium as Corporate Contributor

.github/workflows/backup-all-repos-to-gitlabwh.bash, .github/workflows/backup-all-repos-to-gitlabwh.yml
=> feat: Schedule a backup of all repos

.github/workflows/dtk-unittest.yml, repos/linuxdeepin/dtk-template.json, repos/linuxdeepin/dtkaudiomanager.json, repos/linuxdeepin/dtkbluetooth.json, repos/linuxdeepin/dtkcrypt.json, repos/linuxdeepin/dtkdevice.json, repos/linuxdeepin/dtkdisplay.json, repos/linuxdeepin/dtkio.json, repos/linuxdeepin/dtkmultimedia.json, repos/linuxdeepin/dtknetwork.json, repos/linuxdeepin/dtknetworkmanager.json, repos/linuxdeepin/dtksystem.json, repos/linuxdeepin/dtksystemsettings.json, workflow-templates/call-dtk-unittest.yml
=> feat: add dtk project unittest workflow template

teams.yaml
添加兆芯为企业贡献者
cc @leoliu-oc @tsic404
=> chore: add Zhaoxin as Corporate Contributor

.github/workflows/dtk-unittest.yml
=> fix: switch to pr hash

.github/workflows/doc-check.yml
=> fix: use apricot docker image

.github/workflows/dtk-unittest.yml
=> fix: dtk-unittest not install dependences

.github/workflows/dtk-unittest.yml
=> fix: cannot run mk-build-deps

.github/workflows/dtk-unittest.yml
doesn't use sudo, because docker use root
Log:
=> chore: remove sudo

.github/workflows/dtk-unittest.yml
=> fix: cannot test in workspace

.github/workflows/build-distribution.yml, .github/workflows/dtk-unittest.yml
=> chore: fix yaml lint

.github/workflows/dtk-unittest.yml
=> fix: cannot run dbus

teams.yaml
update grand search maintainers
=> chore: update grand search maintainers

teams.yaml
=> feat: update linglong project member

teams.yaml
=> feat: update linglong project members

.github/workflows/auto-tag.yml, .github/workflows/backup-to-gitlabwh.yml, .github/workflows/build-deb.yml, .github/workflows/build-distribution.yml, .github/workflows/build-linglong.yml, .github/workflows/tag-build.yml, .github/workflows/templates-sync.yml
github action use new setOutput
use env file instead ::set-output::
Log:
=> chore: adapt to new setOutput

.github/workflows/backup-to-gitlabwh.yml
fix new style setoutput with more >> in back to gitlabwh
Log:
=> fix: fix new style setOutput with more >>

.github/workflows/build-distribution.yml
=> fix: remove char 'name='

.github/workflows/cla-check.yml
move partner into partner-allow-email-list
Log:
=> feat: add partner check

teams.yaml
=> feat: update linglong projects

.github/workflows/auto-tag.yml
check translate update before tag
Log:
=> feat: add translate update check

.github/workflows/auto-tag.yml
=> chore: skip step when .tx/config not exist

teams.yaml
Request for DTK maintainer access
=> chore: Update teams.yaml

teams.yaml
add dtkprinter repositories
Log: add dtkprinter repositories
=> chore: add dtkprinter repositories

.github/workflows/auto-tag.yml
some repository does not have transifex branch
Log:
=> chore: update transifex check

organization.yaml, repos/linuxdeepin/xdg-desktop-portal-dde.json, teams.yaml
add xdg-desktop-portal-dde
Log:
=> feat: add xdg-desktop-portal-dde

organization.yaml, repos/linuxdeepin/warm-sched.json, teams.yaml
为 warm-sched 增加 CI 配置与分支保护
cc @electricface
=> chore: add CI configuration for warm-sched

workflow-templates/call-tag-build.yml
fix error call workflow name
Log:
=> fix: fix error call workflow name

.github/workflows/auto-tag.yml
=> chore: skip translation check when .tx/config not exists

.github/workflows/tag-build.yml
=> fix fix tag-build:

teams.yaml
=> feat: add linglong-doc

teams.yaml
Adds the permission configuration for 'deepin-wayland-protocols'.
=> feat: Adds the permission configuration for 'deepin-wayland-protocols'.

.github/workflows/cla-check.yml
make *@deepin.org, *@deepin.com and  *@uniomtech.com as partner's email
Log:
=> chore: make deepin and uniontech as a parnter

teams.yaml
=> chore: add permissions

repos/linuxdeepin/dtknetworkmanager.json
为 dtknetworkmanager 添加文档生成 CI
本次暂不添加文档检查 CI
cc @xzl01
=> chore: add deploy dev docs CI for dtknetworkmanager

.github/workflows/build-distribution.yml
=> fix: archlinux build failed

.github/workflows/build-distribution.yml
=> fix: arch check not checkout to pullrequest

.github/workflows/deploy-dev-doc.yml
=> chore: add sidebar to deploy-dev-docs

.github/workflows/build-distribution.yml
=> chore: update version format

teams.yaml
Add push permission for dtknotifications.
Log: add push permission
=> chore: add push permission for dtknotifications

.github/workflows/build-distribution.yml
=> chore: package add time info

organization.yaml, repos/linuxdeepin/dtknotifications.json
为 dtknotifications 添加 CI 配置
cc @xzl01
=> chore: add CI configuration for dtknotifications

organization.yaml
=> chore: protect release/* branches

repos/linuxdeepin/dtksystemsettings.json
为 dtksystemsettings 增加文档生成配置
cc @xzl01
=> chore: add deploy-dev-docs for dtksystemsettings

repos/linuxdeepin/dde-kwin.json, repos/linuxdeepin/deepin-kwin.json
触发 kwin 项目的工作流同步，便于重新部署
@axylp
=> chore: trigger workflow sync to kwin projects

repos/linuxdeepin/dtkmultimedia.json
为 dtkmultimedia 提供文档生成 CI
cc @xzl01
=> chore: add deploy-doc CI for dtkmultimedia

repos/linuxdeepin/dtkaudiomanager.json, repos/linuxdeepin/dtkdevice.json, repos/linuxdeepin/dtkio.json
为 DTK 的 io/device/audiomanager 项目添加在线文档生成
cc @xzl01
=> chore: add deploy-doc for dtkio/device/audiomanager

.github/workflows/build-deb.yml
=> chore: disable uos build

.github/workflows/deploy-dev-doc.yml
=> feat: add doxygen theme suppot

.github/workflows/auto-tag.yml
sync : and ~ replace from deepin-community
add UNRELEASED will not create tag
log:
=> fix: sync deepin-community fix

.github/workflows/deploy-dev-doc.yml, workflow-templates/call-deploy-dev-doc.yml
由于github pages不支持多版本
添加手动部署文档到codeberg的功能
Log:
=> feat: deploy docs to codeberg

.github/workflows/auto-tag.yml
remove epoch and reversion
log:
=> fix: remove epoch and reversion

.github/workflows/auto-tag.yml
update get-emial action,and add token
log:
=> fix: update get-email action

.github/workflows/auto-tag.yml
=> fix: auto-tag

.github/workflows/build-distribution.yml
=> chore: diable deepin 20 build

.github/workflows/build-distribution.yml
=> chore: enable build-distribution debian

.github/workflows/deploy-dev-doc.yml
=> feat: add support qml doxygen

teams.yaml
add deepin-ocr-plugin-manager repositories
Log: add deepin-ocr-plugin-manager repositories
=> chore: add deepin-ocr-plugin-manager repositories

repos/linuxdeepin/deepin-wayland-protocols.json
- deepin-kwin
- deepin-wayland-protocols
=> chore: update repos

teams.yaml
add ncnn、opencv-mobile repositories
Log: add ncnn、opencv-mobile repositories
=> chore: add ncnn、opencv-mobile repositories

repos/linuxdeepin/ncnn.json, repos/linuxdeepin/opencv-mobile.json
=> chore: add ncnn and opencv-mobile

.github/workflows/deploy-dev-doc.yml
=> fix: change doxyqml install method

repos/linuxdeepin/deepin-wayland-protocols.json
=> chore: remove deepin-wayland-protocols cppcheck

teams.yaml
=> add DDE new projects

.gitattributes, organization.yaml, repos/linuxdeepin/dde-api-proxy.json, repos/linuxdeepin/dde-appearance.json, repos/linuxdeepin/dde-application-manager.json, repos/linuxdeepin/dde-cooperation.json, repos/linuxdeepin/dde-permission-manager.json, repos/linuxdeepin/dde-session.json, repos/linuxdeepin/dde-widgets.json, repos/linuxdeepin/deepin-desktop-theme.json
为 v23 beta 集成的 dde 应用添加 CI 配置与分支保护
=> chore: CI and branch configuration for dde v23 repos

.github/workflows/build-distribution.yml
obs will provide debian build
Log:
=> chore: move debian to obs

teams.yaml
Add triage permission for DTK to acquire assignment ability.
Log: add triage permission for DTK
=> chore: add triage permission for DTK

teams.yaml
Update linglong releated teams config according to the maintainer list.
=> Update teams config

teams.yaml
Signed-off-by: Tianyu Chen <chentianyu1@uniontech.com>
=> feat: add UTsweetyfish

teams.yaml
add dfm、pdf project teamers
Log: update teamers
=> feat: update file manager teamers

.github/workflows/deploy-dev-doc.yml
doxyqml安装时报错缺少setuptools依赖
Log:
=> fix: doxyqml installaction fialed

teams.yaml
update teamer info
Log: update teamer info
Bug:
=> feat: update project teamer

.github/workflows/license-check.yml
=> chore: update ubuntu mirror

.github/workflows/chatOps.yml
=> chore: disable merge comment for chatopt

organization.yaml, repos/linuxdeepin/deepin-upgrade-manager.json, teams.yaml
- feat: add deepin-upgrade-manager
- feat: add deepin-upgrade-manager CI
=> feat: add deepin-upgrade-manager CI

teams.yaml
add team maintainer
Log: add team maintainer
=> feat: add team maintainer

teams.yaml
Add ArchieMeng to deepin-sysdev and Multimedia-audio-video
=> chore: Add ArchieMeng to teams.yaml

teams.yaml
Add asterwyx to dde-maintainer.
Log: add asterwyx to dde-maintainer
=> chore: add dde maintainer

repos/linuxdeepin/dde-app-services.json
Remove issue's fallback to linuxdeepin
Log: none
Influence: none
=> chore: add unit test issue template for dde-app-services

organization.yaml, repos/linuxdeepin/dde-display.json
=> feat: add dde-display workflow

.github/workflows/build-distribution.yml
=> chore: disable archlinux build

repos/linuxdeepin/dde-widgets.json
Remove issue's fallback to linuxdeepin.
=> chore: Override issue template for dde-widgets

teams.yaml
=> feat: add deepin-system-upgrade

repos/linuxdeepin/dtkbluetooth.json
=> feat: add dtkbluetooth docs ci

organization.yaml
=> chore: reconfigure some repo's branch protection

teams.yaml
Add shanshany to dde for `dde-widgets`.
=> chore: Add a member to dde group

teams.yaml
=> feat: add deepin-service project

repos/linuxdeepin/deepin-service.json
为 deepin-service 添加 CI 配置与分支保护
cc @Groveer
=> chore: add CI and branch protection for deepin-service

organization.yaml, repos/linuxdeepin/deepin-service-manager.json, teams.yaml
=> chore: rename deepin-service to deepin-service-manager

repos/linuxdeepin/util-dfm.json, teams.yaml
添加缺失的 CI，添加维护 network-proxy 的团队
cc @black-desk @max-lvs
=> chore: add missing CI, add team for network-proxy

organization.yaml, repos/linuxdeepin/deepin-system-upgrade.json
为 deepin-system-upgrade 添加 CI 配置
cc @18202781743
=> chore: add CI configuration for deepin-system-upgrade

organization.yaml, repos/linuxdeepin/go-gir.json, repos/linuxdeepin/need-update
重命名 go-gir-generator 仓库到 go-gir
=> chore: rename go-gir-generator to go-gir

teams.yaml
=> chore: 更新多媒体成员

teams.yaml
adding members to deepin-icon-theme and deepin-desktop-theme
=> chore: adding members

teams.yaml
add write permission of deepin-face and fcitx
Log: add write permission of deepin-face
=> chore: add write permission of deepin-face

.github/workflows/chatOps.yml
=> fix(chatops): obs check comment error

.github/workflows/chatOps.yml
=> fix(chatops): change chat bot name

.github/workflows/auto-tag.yml
when go.mod file exists create tag with v prefix
log:
=> feat: when go.mod exists create tag with v prefix

.github/workflows/auto-tag.yml
Reverts linuxdeepin/.github#502
=> Revert "feat: when go.mod exists create tag with v prefix"

teams.yaml
=> chore: add dtk permission for dtk team

.github/workflows/chatOps.yml
cancel use secrets, use hook id directly
log:
=> fix(chatops): HOOK_ID can't read from secrets

repos/linuxdeepin/dtkaudiomanager.json, repos/linuxdeepin/dtkbluetooth.json, repos/linuxdeepin/dtkcore.json, repos/linuxdeepin/dtkdeclarative.json, repos/linuxdeepin/dtkdevice.json, repos/linuxdeepin/dtkgui.json, repos/linuxdeepin/dtkio.json, repos/linuxdeepin/dtkmultimedia.json, repos/linuxdeepin/dtknetworkmanager.json, repos/linuxdeepin/dtknotifications.json, repos/linuxdeepin/dtksystemsettings.json, repos/linuxdeepin/dtkwidget.json
=> fix: fix error path

.github/workflows/deploy-dev-doc.yml, .github/workflows/doc-check.yml, .github/workflows/dtk-unittest.yml
add use deepin obs develop software package repo
log:
=> chore(CI): doc check workflow use beige environment

repos/linuxdeepin/dde-control-center.json
Log: deploy controlcenterci doc ci
=> chore: deploy controlcenter doc ci

teams.yaml
=> chore: add new developer

.github/workflows/deploy-dev-doc.yml, .github/workflows/doc-check.yml
=> chore(CI): beige image use base tag

teams.yaml
update dde-file-manager team members
Log: update dde-file-manager team members
Bug: no
=> fix: update dde-file-manager team members

.github/workflows/organization-manager.yml
=> feat: organization manager add workflow_dispatch

.github/workflows/deploy-dev-doc.yml
=> fix: repository name add owner prefix

teams.yaml
=> chore: add application-manager team

.github/workflows/auto-integration-pr.yml
miss ',' when add 'per_page' support
log:
=> fix(chatopt): github js SyntaxError

.github/workflows/auto-integration-pr.yml
and change integration pr branch name rule
log
=> fix(CI): default integration milestone incorrect

.github/workflows/auto-integration-pr.yml
now beige integration use latest milestone by default
log:
=> feat(CI): /integrate use latest milestone by default

.github/workflows/auto-integration-pr.yml
used for update and record integration change
log:
=> feat(CI): /integrate add timestamp

teams.yaml
升级工具添加到 dde 组，便于 dde 组互相 review
cc @18202781743
=> chore: add upgrade manager to dde-maintainer team

teams.yaml
apply to join dde-maintainer team
Log: apply to join dde-maintainer team
=> chore: apply to join deepin team

workflow-templates/cppcheck.yml
fix: Update cppcheck.yml
根据github最新文档，做了一些微调
=> fix: Update cppcheck.yml

.github/workflows/auto-integration-pr.yml
remove milestone, use latest milestone by default
=> chore(CI): Update /integrate command args

teams.yaml
=> chore: update teams.yml

teams.yaml
add deepin-unioncode team
Log: team change
=> chore: add deepin-unioncode team

.github/workflows/auto-integration-pr.yml
multi repos integrate with topic need append at one integration pr
=> fix(CI): /integrate $topic error

.github/workflows/auto-integration-pr.yml
=> fix(CI): map filter error

.github/workflows/auto-integration-pr.yml
fix for integration with topics
log:
=> chore(CI): intergration checkout if branch existed

.github/workflows/auto-tag.yml, .github/workflows/backup-to-gitlab.yml, .github/workflows/call-clacheck.yml, .github/workflows/call-transfer-issues.yml, .github/workflows/cla-check.yml, .github/workflows/doc-check.yml, .github/workflows/transfer-issues-func.yml, workflow-templates/backup-to-gitlab.yml, workflow-templates/call-build-distribution.yml, workflow-templates/call-build-linglong.yml, workflow-templates/call-clacheck.yml, workflow-templates/call-deploy-dev-doc.yml, workflow-templates/call-doc-check.yml, workflow-templates/call-transfer-issues.yml
Now use secrets to acquire APP_ID, all workflow call secrets change to inherit.
=> chore: use secrets for app id

.github/workflows/auto-integration-pr.yml
=> chore(CI): integration message add repository name

teams.yaml
add rust-tools team
Log: add rust-tools team
=> chore(CI): add rust-tools for utshell utsudo

teams.yaml
update deepin-diskmanager teamers
Log: update deepin-diskmanager teamers
Bug: no
=> chore: update deepin-diskmanager teamers

.github/workflows/auto-integration-pr.yml, .github/workflows/auto-tag.yml, .github/workflows/chatOps.yml, .github/workflows/transfer-issues-func.yml
=> fix(CI): github scripts get token error

.github/workflows/auto-tag.yml
=> fix: typo of auto-tag.yml

.github/workflows/auto-tag.yml
Add a newline character to tag message
=> fix: update commit message of auto-tag

repos/linuxdeepin/dtk.json
Repo dtk now needs some workflows. Sync it from .github.
Log: add workflows for dtk
=> chore: add workflows for dtk

teams.yaml
添加启动盘制作和下载器维护权限
log: 添加启动盘制作和下载器维护权限
@BLumia
=> fix: 添加启动盘制作和下载器维护权限

repos/linuxdeepin/dtk.json
Dest of dtk workflows is wrong. Correct it.
Log: correct dest
=> fix: correct dest

teams.yaml
Create a new group and add push permission for ci robot.
=> chore: add permission for ci robot

.github/workflows/auto-integration-pr.yml, .github/workflows/chatOps.yml
Sometimes Debian build errors require delayed processing
log:
=> feat(chatOpt): Add /forcemerge command for force merge

.github/workflows/auto-integration-pr.yml
integrate with topic need specify base for pr create
log:
=> fix(CI): create integrate pr error

teams.yaml
=> chore: add dtk6 repo

.github/workflows/auto-integration-pr.yml
使用不切换分支的方式修改integration.yml,确保peter-evans/create-pull-request正确提交修改后的内容
log:
=> fix(CI): integrate pr commit content incorrect

organization.yaml, repos/linuxdeepin/deepin-deepinid-client.json, repos/linuxdeepin/deepin-deepinid-plugin.json, teams.yaml
为 deepinid 相关的两个项目添加分支保护与 CI
cc @Decodetalkers
=> chore: add CI and protection for deepinid-related repo

repos/linuxdeepin/dtk6core.json, repos/linuxdeepin/dtk6declarative.json, repos/linuxdeepin/dtk6gui.json, repos/linuxdeepin/dtk6widget.json, repos/linuxdeepin/qt6integration.json, repos/linuxdeepin/qt6platform-plugins.json
Add configurations for synchronizing files to dtk6*.
Log: add dtk6 synchronization configs
=> feat: add dtk6 synchronization configs

.github/workflows/doc-check.yml
Add topic repo to sourcelist if it's a topic build.
Log: add obs topic build support
=> feat: add obs topic build support

teams.yaml
=> chore: add deepin-codeporting team

.github/workflows/backup-to-gitee.yml
之前的gitee组织因企业版过期, 无法再创建仓库, 改用新的仓库
Log:
=> feat: Sync to new gitee organization

.github/workflows/backup-to-gitee.yml
=> feat: gitee create opensource repository

teams.yaml
=> chore: add deepin-ai-daemon team

teams.yaml
=> chore: add deepin-im

teams.yaml
Description: 申请letmego仓库访问权限
Log: 申请letmego仓库访问权限
=> fix: 申请letmego仓库访问权限

.github/workflows/commitlint.yml
=> Update commitlint.yml [actions/checkout@v3]

teams.yaml
Description: 测试部新开源3个项目，现申请访问权限
Log: 测试部新开源3个项目，现申请访问权限
=> fix: 测试部新开源3个项目，现申请访问权限

organization.yaml, teams.yaml
add dde-file-manager-extensions to repositories
Log: add dde-file-manager-extensions to repositories
Bug: no
=> chore: add dde-file-manager-extensions to repositories

teams.yaml
Add bbs-mobile-web to the deepin-home team
=> feat: Update teams.yaml

teams.yaml
=> chore: add permissions for dde-shell

repos/linuxdeepin/dde-shell.json
=> chore: add CI workflow for dde-shell

.github/workflows/auto-integration-pr.yml
=> chore(CI): Remove unused 'order' field at integrate workflow

teams.yaml
add new member
log: add new member
@BLumia
=> chore: add new member

teams.yaml
=> chore: add new deepin-unioncode member

teams.yaml
=> chore: rename member in deepin-unioncode

.github/workflows/chatOps.yml
1. 取消obs webhook查找范围限制,可能会增加查找时间,因此添加obs查找提醒
2. 查询过程添加基于webhook payload中包含的pr number的过滤,提高查找精确度
以上两项优化会提高成功率,但是时间会有所增加
log:
=> chore(CI): Optimize '/check obs' to improve triggering success rate

repos/linuxdeepin/dde-file-manager-extensions.json
=> chore(CI): Add github action workflows for dde-file-manager-extensions

teams.yaml
=> chore: change deepin-unioncode member

teams.yaml
=> chore: add dde-maintainer menber

.github/workflows/deploy-dev-doc.yml, .github/workflows/doc-check.yml
=> fix: allow break system package

.github/workflows/cla-check.yml
add renovate[bot] dependabot[bot]
Log:
=> feat: add bot to cla

.github/workflows/deploy-dev-doc.yml, .github/workflows/doc-check.yml
Install doxyqml, resolvelib and coverxygen from develop repository.
Log: use system python packages
=> chore: use system python packages

.github/workflows/auto-tag.yml
1. tag创建成功后创建release
2. tag创建成功后通知同项目下open状态下的pr有tag更新,提醒进行rebase操作Y
log:
=> feat(CI): Create release for tag

teams.yaml
=> chore: add deepin-osconfig config

.github/workflows/deploy-dev-doc.yml, .github/workflows/doc-check.yml, .github/workflows/dtk-unittest.yml
目前beta2和beta3主仓库存在冲突,不能混用,先去掉beta2主仓库
log:
=> chore(CI): Remove beige beta2 repo addr

teams.yaml
add dde-file-manager-external to team dde-file-manager.
=> chore: add dde-file-manager-external

.github/workflows/dtk-unittest.yml
Support pass changelog version to cmake to enable versioned unit test.
Log: support pass changelog version to cmake
=> feat: support pass changelog version to cmake

.github/workflows/auto-tag.yml
=> chore(CI): Rebase reminder optimization

teams.yaml
Update mulitmedia team members
Log: Update mulitmedia team members
=> chore: Update multimedia team members

teams.yaml
=> chore: add sysdev

teams.yaml
add migration-tools project team info
Log: Create migration-tools project team
=> feat: Create migration-tools project team

.github/workflows/cla-check.yml
=> chore: add transifex-integration[bot] to cla allowlist

repos/linuxdeepin/linglong-pica.json
=> feat: add repos for linglong-pica

teams.yaml
add pkgs-categorizer project team info
Log: Create pkgs-categorizer project team
=> feat: Create pkgs-categorizer project team

teams.yaml
add newcomer to team
Log: no
Bug: no
=> chore: add newcomer to team

teams.yaml
Description: 
接领导要求，将修改 deepin-autotest-framework 仓库名称为：youqu
Log:
=> fix: 修改 deepin-autotest-framework 仓库名称为：youqu

teams.yaml
add deepin-desktop-base sysdev team
Log:
=> chore: add deepin-desktop-base sysdev team

teams.yaml
=> feat: Create deepin-deb-fix project team

repos/linuxdeepin/deepin-deb-fix.json
=> chore: add CI workflow for deepin-deb-fix

.github/workflows/auto-integration-pr.yml, .github/workflows/auto-tag.yml, .github/workflows/chatOps.yml, .github/workflows/transfer-issues-func.yml
新版本require存在问题,需要等https://github.com/octokit/octokit.js/pull/2665 合并才能正常
=> fix(CI): use old octokit version to support require

.github/workflows/chatOps.yml
=> chore(CI): Add limit for get pr info

organization.yaml, repos/linuxdeepin/ddm.json, teams.yaml
=> chore: add ddm

teams.yaml
add dtkio to dde-file-manager group
Log:
=> chore: add dtkio to dde-file-manager group

teams.yaml
add member to deepin ai daemon
=> chore:  add member to deepin ai daemon

teams.yaml
=> chore: add groveer to treeland team

teams.yaml
=> chore: add mhduiy to dde-maintainer

teams.yaml
add member
Log: add dde-printer member
=> chore: add dde-printer member

teams.yaml
add members
Log: add dtk members
=> chore: add dtk members

teams.yaml
add mhduiy to DTK member
Log: add mhduiy to DTK member
=> chore: add mhduiy to DTK member

organization.yaml, teams.yaml
Log: update the new project and newcomers
Bug: no
=> chore: update the new project and newcomers

teams.yaml
add new teams and add members
Log: add new teams
=> chore: add new teams

teams.yaml
add deepin-network-displays project
Log:
=> chore: add deepin-network-displays

.github/workflows/api-check.yml, .github/workflows/static-check.yml, repos/linuxdeepin/dde-dock.json, repos/linuxdeepin/dde-file-manager.json
add check for go and shell
Log: 增加对go和shell的检查
=> feat: add check for go and shell

teams.yaml
add dde-tray-loader for dde-maintainer
log: as title
=> chore: add dde-tray-loader repo

.github/workflows/debian-check.yml
update debian check for key words
Log: 修复debian检查敏感词检查
=> fix: update debian check for key words

organization.yaml, repos/linuxdeepin/dde-tray-loader.json
action CI for dde-tray-loader
Log:
=> chore: action CI for dde-tray-loader

.github/workflows/static-check.yml
update golangci-lint config set condition
Log: 修复golangci-lint配置设置条件
=> fix: update golangci-lint config set condition

teams.yaml
add deepin-sbom-tools repo member and permission
=> chore: add deepin-sbom-tools repo

teams.yaml
=> chore: add dtklog repo

teams.yaml
add deb check approve refer to gerrit system group.
Log:
Change-Id: Ia0f69da7e5537f7807b831126cc381e46bc016e7
- [✔ ] config change of team add
- [✔ ] refer to team that laihongsheng@uniontech.com claim
=> feat：add deb check approve team

teams.yaml
=> feat: add treeland member team

.github/workflows/api-check.yml, .github/workflows/debian-check-keys.yml, .github/workflows/debian-check-prefix.yml, .github/workflows/debian-check-version.yml, .github/workflows/debian-check.yml, workflow-templates/call-api-check.yml, workflow-templates/call-debian-check.yml, workflow-templates/call-static-check.yml
add comment in PR
Log: 增加PR检查结果注释
=> chore(ci): add comment in PR

.github/workflows/debian-check-keys.yml
fix workflow strategy set condition
Log: 修复矩阵运行条件
=> chore(ci): fix workflow strategy set condition

repos/linuxdeepin/dtk6log.json, repos/linuxdeepin/dtklog.json
=> chore: add workflows for dtklog/dtk6log

.github/workflows/debian-check-keys.yml, .github/workflows/debian-check-post.yml, .github/workflows/debian-check-prefix.yml, .github/workflows/debian-check-version.yml, .github/workflows/debian-check.yml
add reviewer for debiancheck
Log: debian检查增加reviewer
=> chore(ci): add reviewer for debiancheck

.github/workflows/debian-check-post.yml
update add team token
log: 更新token
=> chore(CI): update add team token

.github/workflows/debian-check-keys.yml, .github/workflows/debian-check-post.yml
fix files argument list too long error
Log: 优化PR变更信息太多导致参数太长报错
=> chore(CI): fix files argument list too long error

.github/workflows/debian-check-post.yml
update review request set
Log: 更新检查review人员设置
=> chore(CI): update review request set

teams.yaml
=> add self to dde-maintainer

teams.yaml
allow treeland team triage developer-center
Log:
=> chore: update team

teams.yaml
add swq11 to dde-maintainer
Log:
=> chore: add self to dde-maintainer

teams.yaml
chore: Remove departed employees
Remove follow id:
- realwujing
We extend our sincere gratitude for his dedicated
work to deepin-kernel-team.
=> chore: Remove departed employees

.github/workflows/debian-check-post.yml, .github/workflows/debian-check.yml
add remove specified reviewer if recheck pass
Log: 当检查通过, 删除指定reviewer
=> chore(CI): add remove specified reviewer if recheck pass

teams.yaml
add xionglinlin caixr23 ECQZXC to dde-maintainer
Log:
=> chore: add user to dde-maintainer

.github/workflows/cla-check.yml
=> fix: unable to run cla when sign with space at the end

teams.yaml
=> chore:  add members to ai daemon

teams.yaml
=> chore:  add dtkai members

.github/workflows/api-check.yml, .github/workflows/static-check.yml
update check status get ways
Log: 更新检测结果获取方式
=> chore(CI): update check status get ways

organization.yaml, repos/linuxdeepin/deepin-dummyapps.json, teams.yaml
为 deepin-dummyapps 添加 CI 、权限和分支保护
Log:
=> chore: add CI and branch protect for deepin-dummyapps

teams.yaml
dde 添加deepin-service-plugins项目
=> chore: dde 添加deepin-service-plugins项目

repos/linuxdeepin/treeland-protocols.json, teams.yaml
=> chore: add treeland-protocols permissions

teams.yaml
add new member to dde-file-manager
Log: add new member to dde-file-manager
=> chore: add new member to dde-file-manager

teams.yaml
add new members to fcitx project
Log: add new members to fcitx project
=> chore: add new members to fcitx project

.github/workflows/doc-check.yml
=> chore: disable installCoverxygen

.github/workflows/cla-check.yml
=> chore: add deepin-ci-robot to the whitelist

teams.yaml
update project team
Log: update project team
=> chore: update project team

teams.yaml
=> chore: dde添加dde-dialog项目

teams.yaml
修改有趣等测试仓库管理员
添加管理员:wangp-h,lyf0601
=> 修改有趣等测试仓库管理员

teams.yaml
=> feat: add deepin-prime

teams.yaml
Log: add lzwind to fcixt5 team
=> chore: add lzwind to fcixt5 team

teams.yaml
Add linuxdeepin/summer-ospp to summer-ospp team
=> chore: add summer-ospp team

teams.yaml
=> chore: add deepin-update-ui

repos/linuxdeepin/dde-kwin.json, repos/linuxdeepin/deepin-kwin.json
=> chore: clear up workflow for dde-kwin/deepin-kwin

teams.yaml
=> chore: add deepin-scanner

teams.yaml
=> feat: update xzl01's repo

teams.yaml
=> add jianhope to teams

teams.yaml
=> chore: add deepin-icon-theme to dde-maintainer

teams.yaml
=> feat: add deepin / dde settings default repo

teams.yaml
=> chore: add qaqland

teams.yaml
=> chore: add linglong team
