linuxdeepin/.github

.github/workflows/templates-sync.yml

sync failed when change file "repos/linuxdeepin/.gitkeep"
limit sync action's suffix
Log:

fix: actions sync failed

---

organization.yaml

project无法开启,暂时去掉
分支保护排除管理员,以便于机器人推送

fix: 项目管理同步失败

---

.github/workflows/backup-to-gitlab.yml

备份到gitlab的工作流只运行在linuxdeepin组织下工作
避免fork仓库触发备份任务
Log: fork仓库不触发备份工作流

feat: 备份工作流只在linuxdeepin工作

---

workflow-templates/call-build-deb.yml

fix: call build-deb miss uses

---

.github/workflows/backup-to-gitlab.yml
repos/linuxdeepin/deepin-gtk-theme.json
repos/linuxdeepin/deepin-manual.json
repos/linuxdeepin/deepin-music.json
workflow-templates/backup-to-gitlab.yml
workflow-templates/call-build-deb.yml

1. 清理已执行过的的'删除'配置
2. 只有工作流变动不再触发编译构建
3. 由于备份仓库工作流每次都同步整个仓库,使用仓库名做并发键
Log:

feat: 优化性能

---

teams.yaml

修复 teams.yaml 中的 deepin-face 一组配置
相关：https://github.com/linuxdeepin/.github/pull/85
Log: 修复 teams.yaml 中的 deepin-face 一组配置

fix: teams.yaml for deepin-face team

---

.github/workflows/call-chatOps.yml
.github/workflows/chatOps.yml

GitHub Action Token not trigger other workflows
It is GitHub design to avoid infinity triggers loop.
See: https://github.com/ad-m/github-push-action/issues/32
Log:

fix: Merge does not trigger other workflows

---

workflow-templates/call-build-deb.yml
workflow-templates/cppcheck.yml

Does not limit the 'types' field of the pull_request_target
Log:

feat: Run triggers workflow when PR reopened

---

organization.yaml
repos/linuxdeepin/dareader.json
repos/linuxdeepin/dde-daemon.json
repos/linuxdeepin/dde-session-shell.json
repos/linuxdeepin/dde-session-ui.json
repos/linuxdeepin/dde-wldpms.json
repos/linuxdeepin/dde-wloutput-daemon.json
repos/linuxdeepin/deepin-desktop-schemas.json
repos/linuxdeepin/deepin-network-proxy.json
repos/linuxdeepin/deepin-sound-theme.json
repos/linuxdeepin/default-settings.json
repos/linuxdeepin/dpa-ext-gnomekeyring.json
repos/linuxdeepin/go-dbus-factory.json
repos/linuxdeepin/go-gir-generator.json
repos/linuxdeepin/go-lib.json
repos/linuxdeepin/go-x11-client.json
repos/linuxdeepin/startdde.json

为 dde 相关项目设置分支保护和 CI 检查
@wubw1992 请关注：
- 此 PR 只包含了截至目前已迁移完成的项目
- 非 C++ 项目未设置 cppcheck 检查
- 分支保护仅保护 master，若项目在使用非 master 分支进行开发，请切换到 master
- 在合入前，部分项目若包含 `.github/workflows/build.yaml` ，则请删除此文件（此 CI 应该是跑不过的，合入后会因为此 CI 失败而影响合并）

chore: add CI check and branch protection to dde repos

---

organization.yaml
repos/linuxdeepin/deepin-ab-recovery.json

ab-recovery 项目 CI 和分支保护
这个 PR 后，dde 相关的组件应该已经全部迁移完成了

chore: ab-recovery CI and branch config

---

teams.yaml

添加DDE团队其他成员到github的linuxdeepin
Log: 添加DDE团队成员到github的linuxdeepin

chore: Add other members to team of DDE

---

teams.yaml

处理用户名不存在问题，对应的用户名已联系对应人员确认
错误的用户名由 https://github.com/linuxdeepin/.github/pull/120 引入
Log: 处理用户名不存在问题

fix: username does not exist

---

repos/linuxdeepin/dtkcommon.json

dtkcommon 不需要 cppcheck 检查，检查肯定会失败（ https://github.com/linuxdeepin/dtkcommon/pull/7 ）
Log: dtkcommon 不需要 cppcheck 检查

fix: dtkcommon doesn't neet cppcheck

---

organization.yaml
repos/linuxdeepin/deepin-album.json
repos/linuxdeepin/deepin-draw.json
repos/linuxdeepin/deepin-image-viewer.json
repos/linuxdeepin/deepin-movie-reborn.json
repos/linuxdeepin/deepin-ocr.json
repos/linuxdeepin/image-editor.json

为 image-editor 和其它五个项目配置 CI
Log: 为 image-editor 和其它五个项目配置 CI
可能相关：
https://github.com/linuxdeepin/developer-center/issues/2236
https://github.com/linuxdeepin/developer-center/issues/2234

chore: CI and branch config for image-editor and 5 others

---

organization.yaml
repos/linuxdeepin/deepin-boot-maker.json
repos/linuxdeepin/deepin-clone.json

deepin-boot-maker 和 deepin-clone 的分支保护和 CI 配置
需等待 boot-maker 就绪后再合入。
Log:

chore: config for boot-maker and clone

---

organization.yaml
repos/linuxdeepin/deepin-gomoku.json
repos/linuxdeepin/deepin-lianliankan.json
teams.yaml

为连连看和五子棋项目配置 CI 和分支保护
需等待连连看和五子棋项目就绪后再合入
Log:

chore: ci config and branch protection for game proj

---

repos/linuxdeepin/deepin-gomoku.json

五子棋还在使用 dev 作为主线分支名称，所以修改配置
Log:

fix: deepin-gomoku currently using dev branch

---

organization.yaml
repos/linuxdeepin/dde-app-services.json

chore: CI and branch config for dde-app-services

---

repos/linuxdeepin/deepin-voice-note.json

chore: CI and branch config for deepin-voice-note

---

organization.yaml
repos/linuxdeepin/deepin-turbo.json

deepin-turbo 的 CI 配置和分支保护，也补充了 voice note 的分支保护
注意：
其它事项：
- turbo 的 debian/control 声明的依赖应该需要改一下（[这里](https://github.com/linuxdeepin/deepin-turbo/blob/427439da4ba6daf87290a931c48a56cb1eba973d/debian/control#L13)）
- README 里的 maintainer...?

chore: CI and branch config for deepin-turbo

---

.github/workflows/build-deb.yml

The conditional is always true due to a github action syntax error
Log:

fix: apicheck not pass due to action syntax error

---

organization.yaml
repos/linuxdeepin/deepin-diskmanager.json

chore: CI and branch config for deepin-diskmanager

---

teams.yaml

将kvu-display改名为dde-wloutput后上传github
Log: 上传dde-wloutput到github
Influence: github

chore: 上传dde-wloutput项目到github

---

organization.yaml
repos/linuxdeepin/dde-wloutput.json

chore: wloutput CI and branch config

---

organization.yaml
repos/linuxdeepin/deepin-fcitxconfigtool-plugin.json

chore: add CI and branch protection for fcitxconfigtool-plugin

---

organization.yaml

现在在新建 issue 时，向导会导向 developer-center，所以可以开启 issue 面板了。

fix: enable issue board for each repository

---

organization.yaml
repos/linuxdeepin/dde-device-formatter.json
repos/linuxdeepin/deepin-screensaver.json
repos/linuxdeepin/disomaster.json

chore: CI and branch config for DFM related repos

---

repos/linuxdeepin/deepin-manual.json

仓库太大，比较耗 gitee 容量，暂时只备份到 gitlab
Log:

chore: remove mirror sync for deepin-manual

---

organization.yaml
repos/linuxdeepin/docparser.json

docparser 分支保护和 CI 配置

---

organization.yaml
repos/linuxdeepin/dde-printer.json
repos/linuxdeepin/deepin-graphics-driver-manager.json

chore: printer and graphics-driver-manager config

---

organization.yaml
repos/linuxdeepin/dde-calendar.json

chore: CI and branch protection for dde-calendar

---

organization.yaml
repos/linuxdeepin/deepin-devicemanager.json
repos/linuxdeepin/deepin-reader.json

chore: CI and branch config for reader and devicemanager

---

workflow-templates/call-build-deb.yml

when merged re call build, use new github event name
Log: when merged re call build

fix: when merged re call build

---

teams.yaml

将部分团队的维护成员的 maintain 权限下调至 write。
调整后，项目组合并 PR 将需要 PR 发起人或维护者使用 `/merge` 命令进行合并，CI 检查的状态不再能忽略。
此 PR 并非调整了所有 maintain 权限的团队，在此 PR 无误后，将调整其它剩余仍具有 maintain 权限的团队的权限。

chore: adjust maintain role to write for some teams

---

teams.yaml

下调剩余项目组 maintain 权限至 write。
注：linglong-hub 与 open-source-students 相关的权限并未下调。
相关：https://github.com/linuxdeepin/.github/pull/271

chore: change maintain permission to write

---

repos/linuxdeepin/dtkwidget.json

fix send lincense to dtkwidget instead of doc chekc
Log: error send license check

fix: error send license instead of doc check

---

.github/workflows/license-check.yml

Log: use fold to show the license-check message if sometime the message
is too long

feat(commit): use fold show license-check

---

.github/workflows/commitlint.yml

使用新的 commit 检查工作流，以解决 [commit 信息 body 中包含 `#` 会导致检查失败的情况](https://github.com/linuxdeepin/developer-center/issues/3122)。
测试：
- Action https://github.com/peeweep-test/.github/blob/main/.github/workflows/commitcheck.yml
- PR（失败时）：https://github.com/peeweep-test/.github/pull/17
- PR（成功时）：https://github.com/peeweep-test/.github/pull/19
Resolve https://github.com/linuxdeepin/developer-center/issues/3122

chore: use the new conventional commit checker

---

.github/workflows/commitlint.yml

新的需要一些测试情况来了解失败的原因，此处允许新的检查失败，并在其失败时回退到旧的检查。
相关：https://github.com/linuxdeepin/.github/pull/286 https://github.com/linuxdeepin/developer-center/issues/3122

fix: use new commitlint, use the old one as fallback

---

.github/workflows/commitlint.yml

已确认新的 commitlint 可正常进行检查，不再需要 fallback。
相关：https://github.com/linuxdeepin/.github/pull/291 https://github.com/linuxdeepin/.github/pull/286 https://github.com/linuxdeepin/developer-center/issues/3122

chore: remove commitlint fallback

---

.github/workflows/build-distribution.yml

ftp.us.debian.org is too old
Log:

fix: update debian mirror

---

.github/workflows/build-distribution.yml

should check if archlinux/PKGBUILD exists in the main repository, not the pull request target repository.
Log:

fix: archlinux check

---

repos/linuxdeepin/deepin-desktop-base.json

desktop-base 不是 c++ 项目，不需要相关检查

chore: remove cppcheck from deepin-desktop-base

---

teams.yaml

remove xyruos from maintainers
Log: remove xyruos from deepin-kwin maintainers

fix: remove xyruos from deepin-kwin maintainers

---

repos/linuxdeepin/deepin-icon-theme.json

chore: remove cppcheck from deepin-icon-theme

---

.github/workflows/license-check.yml

许可协议与自述文件合规不再总是通过，对于失败的检查，则直接汇报失败。
若有错误，则错误信息汇报在了 Summary 之中。

chore: don't always report as success for license check

---

.github/workflows/chatOps.yml

~~Avoid the `set-output` command warnings.~~
避免类如 https://github.com/linuxdeepin/deepin-album/actions/runs/3426708520/jobs/5708830268#step:5:43 的警告。

chore: bump actions/github-script to v6

---

issue-templates/config-empty.yml
repos/linuxdeepin/dtkaudiomanager.json
repos/linuxdeepin/dtkbluetooth.json
repos/linuxdeepin/dtkcore.json
repos/linuxdeepin/dtkcrypt.json
repos/linuxdeepin/dtkdeclarative.json
repos/linuxdeepin/dtkdevice.json
repos/linuxdeepin/dtkdisplay.json
repos/linuxdeepin/dtkgui.json
repos/linuxdeepin/dtkio.json
repos/linuxdeepin/dtkmultimedia.json
repos/linuxdeepin/dtknetworkmanager.json
repos/linuxdeepin/dtksystem.json
repos/linuxdeepin/dtksystemsettings.json
repos/linuxdeepin/dtkwidget.json

为 DTK 移除全局的 issue 模板，使用一个空白模板（和普通的完全没配置的情况效果一致，可在[这里](https://github.com/peeweep-test/test/issues)预览效果 ）。
cc @groveer

chore: override global issue template for DTK

---

repos/linuxdeepin/unilang.json

为 Unilang 添加基础的 CI 配置：
1. 镜像仓库备份
2. CLA 签署检查
3. 许可协议合规检查
本次未对下述 CI 进行配置：
1. [Commit 提交信息规范](https://www.conventionalcommits.org/zh-hans/v1.0.0/)检查
2. 自动打包检查
3. 自动打 Tag 支持
4. 合并机器人（`/merge` ，`/check` 等命令支持）
cc @FrankHB

chore: add CI configuration for unilang repo

---

.github/workflows/license-check.yml

鉴于 gitea（1.18 起）和 gitee 都支持 README.zh-CN.md 的写法，此处也放宽限制，允许 .zh-CN.md 表示中文版本。

chore: also allow README.zh-CN.md

---

repos/linuxdeepin/deepin-specifications.json

为 deepin-specifications 仓库配置 CI。
注：仅配置了备份 / CLA 检查以及覆盖全局 issue 模板的配置。

chore: add CI config for deepin-spec repo

---

.github/workflows/call-deploy-dev-doc.yml
.github/workflows/deploy-dev-doc.yml
repos/linuxdeepin/dtkcore.json
repos/linuxdeepin/dtkdeclarative.json
repos/linuxdeepin/dtkgui.json
repos/linuxdeepin/dtkwidget.json

添加在线开发文档生成的支持，并为 DTK 核心组件添加相应的配置。
注：
部署此工作流的项目 *必须* 遵循文档规范，具体而言需要满足下述要求：
1. 文档 **必须** 通过 cmake 名为 `doxygen` 的自定义目标进行生成
2. 生成的文档 **必须** 位于项目生成目录下的 `docs/` 子目录下，其中，网页版文档位于 `docs/html/` 子目录下
3. 文档 **必须** 能够接受通过定义 `DOXYGEN_HTML_EXTRA_STYLESHEET` 的方式指定样式表
4. 部署合入前，需要联系仓库管理员开启仓库的 GitHub Pages 支持并设置为 Action（此 PR 涉及到的项目均已设置完毕，其它项目配置前联系我即可，或也可在 [deepin-devel](https://www.freelists.org/archive/deepin-devel/) 邮件列表申请）
cc @tsic404 @xzl01

feat: online development doc generation support

---

.github/workflows/build-deb.yml

deepin-deb-installer need build on v23 for intergration
log:

fix: open build-deb for deepin-deb-installer

---

repos/linuxdeepin/deepin-ocr-plugin-manager.json

为 ocr 插件管理器添加 CI 配置。
暂未添加分支保护，因为检查现在肯定过不去。
cc @starhcq

chore: add CI for ocr-plugin-manager project

---

organization.yaml
teams.yaml

dtkdisplay has been ported to gerrit, we don't need it on github anymore.
Log: archive dtkdisplay

chore: archive dtkdisplay

---

teams.yaml

移除原本 dde 组权限配置，新增 dde-maintainer 组。
为方便 review 起见，当前 dde-maintainer 组申请的权限为如下仓库：
```yaml
repositories_permissions:
triage:
- developer-center
push:
- go-gir-generator
- go-lib
- go-dbus-factory
- go-x11-client
- dde-api
- dde-qt-dbus-factory
- startdde
- dde-daemon
- deepin-desktop-schemas
- deepin-authentication
- deepin-ab-recovery
- lastore-daemon
- dpa-ext-gnomekeyring
- deepin-network-proxy
- deepin-sound-theme
- dareader
- dde-wldpms
- dde-wloutput-daemon
- dde-wayland-config
- default-settings
- dde-control-center
- dde-session
- dde-session-ui
- dde-session-shell
- dde-dock
- dde-clipboard
- dde-network-core
- dde-launcher
- dde-manual-content
- dde-wallpapers
- deepin-wallpapers
- deepin-wallpapers-nonfree
- dde-polkit-agent
- dde-account-faces
- deepin-gettext-tools
- …
```

chore: add dde-maintainer group

---

teams.yaml

deepin-fcitx5configtool-plugin and deepin-fcitxconfigtool-plugin now are maintained by zsien who is in dde team.
Log: add push permission to fcitx for dde

chore: add push permission to fcitx for dde

---

teams.yaml

feat: Add dde-calendar to deepin-home team

---

teams.yaml

允许 deepin 团队 triage 所有仓库的 issue 与 PR。
移除不再使用的昵称信息。

chore: deepin team can triage all repos

---

.github/workflows/build-deb.yml

可以根据需要开启obs构建,开启方法为仓库添加.obs/workflows.yml,文件例子:https://github.com/deepin-community/template-repository/blob/master/.obs/workflows.yml

chore(CI): cancel jenkins build

---

.github/workflows/chatOps.yml

'/check' or '/check obs' pr comment will trigger webhook resend.
由于用于obs构建的github webhook是基于组织的(linuxdeepin/deepin-community),因此 在进行resend操作之前要进行webhook事件过滤,过滤范围为最近的1000条事件,超过这个范围 的事件应该是无法被resend的
log:

feat(CI): github chat bot add obs webhook resend support

---

.github/workflows/deploy-dev-doc.yml

部署文档的工作流存在错别字,导致文档无法被正确推送
Log:

fix: typo in the workflow of delopy-dev-doc

---

.github/workflows/doc-check.yml

beige base environment don't contains coverxygen by default
log:

fix: doc check miss coverxygen

---

.github/workflows/auto-integration-pr.yml

/cc @myml @babyfengfjx @Zeno-sole @BLumia 
pr中使用`/integrate`命令提交集成的方式会默认直接使用pr的title作为集成单的title，并包含pr提交者的github名称。

chore(CI): use pr title as integration message

---

repos/linuxdeepin/dde-launchpad.json

为 dde-launchpad 添加 CI 配置。
注：分支保护未配置，目前可能会有较短的一小段周期会直接往 master 推更新。技术预览版发布后再配置分支保护。

CI: add CI configuration for dde-launchpad repo

---

.github/workflows/auto-integration-pr.yml

peter-evans/create-pull-request 指定的base和当前工作分支不一样会进行rebase merge操作,导致实际提交内容的变更
log:

fix(CI): integrate pr commit content incorrect

---

teams.yaml

add new file-manager teamers, transfered dde-cooperation to file-manager team.
Log: no
Bug: no

chore: add new file-manager teamers

---

.github/workflows/doc-check.yml

Environment variable GITHUB_REF should be set by action. But doc-check uses a container, environment variables are not inherited by this container. As github context is just a string substitute. It will works in every workflow. Use the github.ref(same as GITHUB_REF) instead to populate GITHUB_REF.
Log: fix GITHUB_REF is null

fix: GITHUB_REF is null

---

.github/workflows/doc-check.yml

github.ref in reusable workflow is set to branch where the workflow file is. Use github.head_ref instead.

fix: github.ref not correct in reusable workflow

---

.github/workflows/dtk-unittest.yml

use ’apt build-dep . ' analysis and install latest depends
log:"

fix(CI):  unit test depends install failed

---

repos/linuxdeepin/deepin-upgrade-manager.json

is golang language project, need ignore cppcheck
log:

chore(CI): Remove deepin-upgrade-manager cppcheck workflow

---

.github/workflows/chatOps.yml

get-token step skiped when use /forcemerge
log:

fix(CI): fix for /forcemerge get github token error

---

.github/workflows/dtk-unittest.yml

linuxdeepin/beige 镜像中可能包含不能公开访问的仓库地址,这里统一做覆盖操作

fix(CI): apt sources.list error

---

teams.yaml

Add permission for deepin-ci-robot.
Log: add permission for deepin-ci-robot

chore: add permission for deepin-ci-robot

---

teams.yaml

Deepin Linux Kernel Runtime Guard,
forked from https://github.com/lkrg-org/lkrg

feat: Create deepin-lkrg project team

---

.github/workflows/api-check.yml
.github/workflows/debian-check-keys.yml
.github/workflows/static-check.yml

add check export func change
Log: 增加检查对外接口修改变动

chore(CI): add check export func change

---

.github/workflows/static-check.yml

fix golangci-lint check error
Log: 修复golangci-lint检查问题

chore(CI): fix golangci-lint check error

---

.github/workflows/api-check.yml
.github/workflows/static-check.yml

update api check rules
Log: 更新api检查审核机制

chore(CI): update api check rules

---

teams.yaml

In order to align issues to the group members
Log: Add triage permissions to deepin-boot-maker group

chore: Add triage permissions to deepin-boot-maker group

---

.github/workflows/api-check.yml
.github/workflows/static-check.yml

add dbus api security check
Log: 增加dbus接口安全检查

chore(CI): add dbus api security check

---

.github/workflows/doc-check.yml

chore: disable doc-check job

---

teams.yaml

add libqapt-qt6
Log: add libqapt-qt6

chore: add libqapt-qt6

---

.github/workflows/license-check.yml

已在 https://github.com/peeweep-test/dde-shell-test/pull/6 测试。

feat(CI): using more up-to-date REUSE for license check

---

teams.yaml

Log: add `wineee` to deepin-kwin-member and deepin-kwin team

chore: add wineee to deepin-kwin team

---

.github/workflows/deploy-dev-doc.yml

切换仓库地址，默认使用testing主仓库加dde develop仓库。

chore: Update deploy-dev-doc.yml

---

.github/workflows/auto-tag.yml

已经有新的翻译更新流程，并且该流程还会导致tag流程失败，因此可以在autotag中去掉。

chore: Update auto-tag.yml

---

teams.yaml

add electricface,qiuzhiqian,Fire-dtx to deepin-immutable-ctl member

chore: add deepin-immutalbe-ctl member

---

teams.yaml

chore: add wjyrich

---

.github/workflows/auto-tag.yml

fix: Update auto-tag.yml
